name: hello-world
on: push
env:
  REPO_SEC: ${{secrets.REPO_SEC}}
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: FirstStep
        run: echo "Hello World!"
      - name: SecondStep
        run: echo $REPO_SEC